"""client

Revision ID: 47c689cc5463
Revises: f5126cbc1aec
Create Date: 2017-07-12 00:34:26.231661

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from auth.models import ApplicationType

# revision identifiers, used by Alembic.
revision = '47c689cc5463'
down_revision = 'f5126cbc1aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(length=50), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('application_type', sqlalchemy_utils.types.choice.ChoiceType(ApplicationType), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token_time', sa.Numeric(precision=8, scale=0), nullable=False),
    sa.Column('allowed_origin', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_type'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('secret')
    )
    op.create_index(op.f('ix_clients_cid'), 'clients', ['cid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_cid'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
