"""add revoke to refresh token

Revision ID: 52f701a24748
Revises: 8aefa387597e
Create Date: 2017-10-28 00:27:28.476170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f701a24748'
down_revision = '8aefa387597e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoke', sa.Boolean(), nullable=True, default=False))
    op.execute("""
        UPDATE refresh_tokens
        SET revoke = 'f'
    """)
    op.alter_column('refresh_tokens', 'revoke', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoke')
    # ### end Alembic commands ###
